services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nails_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nails_db
      POSTGRES_PORT: 5432
      LINE_SIZE: 4
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env

volumes:
  postgres_data: